import React, { useState, useEffect, useCallback } from "react";

import IngredientForm from "./IngredientForm";
import IngredientList from "./IngredientList.js";
import Search from "./Search";

const Ingredients = () => {
  const [userIngredients, setUserIngredients] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    console.log("RENDERING INGREDIENTS", userIngredients);
  }, [userIngredients]);

  const addIngredientHandler = (ingredient) => {
    setIsLoading(true)
    fetch("https://react-hooks-update-ede58.firebaseio.com/ingredients.json", {
      method: "POST",
      body: JSON.stringify(ingredient),
      headers: { "Content-Type": "application/json" },
    })
      .then((response) => {
        setIsLoading(false)
        //response is the Object generated by Firebase
        return response.json();
      })
      .then((responseData) => {
        //response.name contains the auto generated id provided by firebase. It's not javascript/React. This is how Firebase works
        setUserIngredients((prevIngredients) => [
          ...prevIngredients,
          { id: responseData.name, ...ingredient },
        ]);
      });
  };

  const filteredIngredientsHandler = useCallback((filteredIngredients) => {
    setUserIngredients(filteredIngredients);
  }, []);

  const removeIngredientsHandler = (ingredientId) => {
    setIsLoading(true)
    fetch(`https://react-hooks-update-ede58.firebaseio.com/ingredients/${ingredientId}.json`, {
      method: "DELETE",
    }).then(response => {
      setIsLoading(false)
      setUserIngredients((preIngredients) =>
      preIngredients.filter((ingredient) => ingredient.id !== ingredientId)
    );
    })

  };
  return (
    <div className="App">
      <IngredientForm 
      onAddIngredient={addIngredientHandler} 
      loading = {isLoading} />

      <section>
        <Search onLoadIngredients={filteredIngredientsHandler} />
        <IngredientList
          ingredients={userIngredients}
          onRemoveItem={removeIngredientsHandler}
        />
      </section>
    </div>
  );
};

export default Ingredients;
